version: 2

before:
  hooks:
    - go mod tidy

builds:
  - builder: prebuilt
    env:
      - CGO_ENABLED=1
      - BUILD_USER=goreleaser
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: build/mcp-time.{{ .Os }}-{{ .Arch }}
    binary: bin/mybin

archives:
  - formats: ["binary"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
