name: go

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@v6
    - name: go list
      run: go list -json -deps ./... > go.list
    - uses: sonatype-nexus-community/nancy-github-action@main
    - run: make test
    - uses: docker/setup-buildx-action@v3
    - run: make docker-all
