name: go

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@v6
    - name: go list
      run: go list -json -deps ./... > go.list
    - uses: sonatype-nexus-community/nancy-github-action@main
    - run: make test
    - run: make build-all
    - uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: theo01/mcp-time:${{ github.ref_name }}
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
  test-linux-amd64:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - run: docker run --rm theo01/mcp-time:${{ github.ref_name }} --version
  test-linux-arm64:
    needs: build
    runs-on: ubuntu-24.04-arm
    steps:
      - run: docker run --rm theo01/mcp-time:${{ github.ref_name }} --version
  test-macos-amd64:
    needs: build
    runs-on: macos-13
    steps:
      - run: docker run --rm theo01/mcp-time:${{ github.ref_name }} --version
  test-macos-arm64:
    needs: build
    runs-on: macos-15
    steps:
      - run: docker run --rm theo01/mcp-time:${{ github.ref_name }} --version
