name: release

on:
  push:
    tags:
    - v*

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - run: make build-all
      env:
        BUILD_USER: github-action
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          name/app
          ghcr.io/username/app
        # generate Docker tags based on the following events/attributes
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
    - uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        file: docker/Dockerfile
        context: .
        platforms:
          - linux/amd64
          - linux/arm64
          - darwin/amd64
          - darwin/arm64
    - uses: goreleaser/goreleaser-action@v6
      with:
        args: release --clean
        version: '~> v2'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_BRANCH: ${{ vars.BUILD_BRANCH }}
