name: release

on:
  push:
    tags:
    - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.24.0'
    - uses: docker/setup-buildx-action@v3
    - run: make build-all
    - uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: theo01/mcp-time:latest,theo01/mcp-time:${{ github.ref }}
        file: docker/Dockerfile
        platforms:
          - linux/amd64
          - linux/arm64
          - darwin/amd64
          - darwin/arm64
    - uses: goreleaser/goreleaser-action@v6
      with:
        args: release --clean
        version: '~> v2'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_BRANCH: ${{ vars.BUILD_BRANCH }}
        BUILD_USER: ${{ vars.BUILD_USER }}
