name: release

on:
  push:
    tags:
    - v*

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - run: make build-all
      env:
        BUILD_USER: github-action
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          theo01/mcp-time
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
    - uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        file: docker/Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
    - run: make npm-publish-all
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Generate Changelog
      id: generate_changelog
      uses: ffurrer2/extract-release-notes@v2
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        body: ${{steps.generate_changelog.outputs.release_notes}}
        files: build/*
